package aplicativo;


import java.awt.BorderLayout;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 * 
 * @author User
 */
public class Acceso extends javax.swing.JFrame {
    String user = "admin";
    String admin = "123";
    int acmd=0;
    
    public Acceso() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Acceso");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new  ImageIcon(this.getClass().getResource("/Imagenes/Azul.png"));
        JLabel fondo=new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        this.add(fondo, BorderLayout.CENTER);
        this.setLocationRelativeTo(null);
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnIngresar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtContraseña = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnIngresar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancel.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA");

        txtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtContraseñaKeyPressed(evt);
            }
        });

        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnCancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnIngresar))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIngresar)
                    .addComponent(btnCancelar))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
     
        if (String.valueOf(txtUsuario.getText()).compareTo("") == 0 && String.valueOf(txtContraseña.getPassword()).compareTo("") == 0) 
        {
            JOptionPane.showMessageDialog(rootPane, "Usuario y contraseña no digitalizado");
            acmd++;
            if (acmd == 3)
            { 
                dispose();
            }
        }
        else
        {
            if (String.valueOf(txtUsuario.getText()).compareTo(txtUsuario.getText()) == 0 && String.valueOf(txtContraseña.getText()).compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Contraseña no digitalizado");
                acmd++;
                if (acmd == 3)
                {
                    dispose();
                }
            }
            else 
            {
                if (String.valueOf(txtUsuario.getText()).compareTo("") == 0 && String.valueOf(txtContraseña.getPassword()).compareTo(txtContraseña.getText()) == 0) 
                {
                    JOptionPane.showMessageDialog(rootPane, "Usuario no digitalizado");
                    acmd++;
                    if (acmd == 3)
                    {
                        dispose();
                    }
                }
                else
                { 
                    if (String.valueOf(txtUsuario.getText()).compareTo(user) == 0 && String.valueOf(txtContraseña.getText()).compareTo(admin) == 0)
                    {
                        Administracion x = new Administracion();
                        x.setVisible(true);
                        this.dispose();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorrecta", "ERROR DE CODIGO", JOptionPane.ERROR_MESSAGE);
                        acmd++;
                        if (acmd == 3)
                        {
                            dispose();
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    private void txtContraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContraseñaKeyPressed
    
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            if (String.valueOf(txtUsuario.getText()).compareTo("") == 0 && String.valueOf(txtContraseña.getPassword()).compareTo("") == 0)
            {
                JOptionPane.showMessageDialog(rootPane, "Usuario y contraseña no digitalizado");
                acmd++;
                if(acmd == 3)
                {
                    dispose();
                }
            }
            else
            {
                if (String.valueOf(txtUsuario.getText()).compareTo(txtUsuario.getText()) == 0 && String.valueOf(txtContraseña.getText()).compareTo("") == 0)
                {
                    JOptionPane.showMessageDialog(rootPane, "Contraseña no digitalizado");
                    acmd++;
                    if(acmd == 3)
                    {
                        dispose();
                    }
                }
                else
                {
                    if (String.valueOf(txtUsuario.getText()).compareTo("") == 0 && String.valueOf(txtContraseña.getPassword()).compareTo(txtContraseña.getText()) == 0)
                    {
                        JOptionPane.showMessageDialog(rootPane, "Usuario no digitalizado");
                        acmd++;
                        if(acmd == 3)
                        {
                            dispose();
                        }
                    }
                    else
                    {
                        if (String.valueOf(txtUsuario.getText()).compareTo(user) == 0 && String.valueOf(txtContraseña.getText()).compareTo(admin) == 0)
                        {
                            Administracion x = new Administracion();
                            x.setVisible(true);
                            this.dispose();
                        }
                        else
                        {
                            JOptionPane.showMessageDialog(rootPane, "Usuario o contraseña incorecta", "ERROR DE CODIGO", JOptionPane.ERROR_MESSAGE);
                            acmd++;
                            if(acmd == 3)
                            {
                                dispose();
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_txtContraseñaKeyPressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        int estado = JOptionPane.showConfirmDialog(rootPane, "Desea salir", "Confirmar", JOptionPane.YES_NO_OPTION);
        if (estado == JOptionPane.YES_OPTION)
        {
            JOptionPane.showMessageDialog(rootPane, "Aplicación concluida");
            System.exit(0);
        } 
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtContraseña;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
