/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplicativo;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author User
 */
public class Administracion extends javax.swing.JFrame {

    /**
     * Creates new form Administracion
     */
    public Administracion() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Administración de ventas ");
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Centro = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMenu = new javax.swing.JMenu();
        DatosCliente = new javax.swing.JMenuItem();
        JMenu2 = new javax.swing.JMenu();
        Precio = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        RealizarCompra = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        GD = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Salir.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Salir");

        javax.swing.GroupLayout CentroLayout = new javax.swing.GroupLayout(Centro);
        Centro.setLayout(CentroLayout);
        CentroLayout.setHorizontalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroLayout.createSequentialGroup()
                .addGap(0, 673, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        CentroLayout.setVerticalGroup(
            CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CentroLayout.createSequentialGroup()
                .addContainerGap(480, Short.MAX_VALUE)
                .addGroup(CentroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CentroLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23))))
        );
        Centro.setLayer(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Centro.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        JMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Clientes.png"))); // NOI18N
        JMenu.setText("                      ");
        JMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuActionPerformed(evt);
            }
        });

        DatosCliente.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        DatosCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Usuario.png"))); // NOI18N
        DatosCliente.setText("DATOS DEL CLIENTE");
        DatosCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DatosClienteActionPerformed(evt);
            }
        });
        JMenu.add(DatosCliente);

        jMenuBar1.add(JMenu);

        JMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Productos.png"))); // NOI18N
        JMenu2.setText("                      ");
        JMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenu2ActionPerformed(evt);
            }
        });

        Precio.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        Precio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Gallet.png"))); // NOI18N
        Precio.setText("EN STOCK");
        Precio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioActionPerformed(evt);
            }
        });
        JMenu2.add(Precio);

        jMenuBar1.add(JMenu2);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ComprarProd .png"))); // NOI18N
        jMenu1.setText("                       ");

        RealizarCompra.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        RealizarCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Produc.png"))); // NOI18N
        RealizarCompra.setText("REALIZAR COMPRA");
        RealizarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RealizarCompraActionPerformed(evt);
            }
        });
        jMenu1.add(RealizarCompra);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ganancias.png"))); // NOI18N

        GD.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        GD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Ganancias2.png"))); // NOI18N
        GD.setText("GANANCIAS DIARIAS");
        GD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GDActionPerformed(evt);
            }
        });
        jMenu2.add(GD);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Centro)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(Centro, javax.swing.GroupLayout.Alignment.LEADING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Integer estado = JOptionPane.showConfirmDialog(rootPane, "Esta seguro que desea salir");//Salir del aplicativo
        if (estado == 0)
        {
            JOptionPane.showMessageDialog(rootPane, "Aplicación terminada");
            System.exit(0);
        }

        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuActionPerformed

    private void DatosClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DatosClienteActionPerformed
        Gananciasdia b = new Gananciasdia();
        this.Centro.add(b);
        b.show();
        Datos a=new Datos();
        this.Centro.add(a);
        a.show();
        

    }//GEN-LAST:event_DatosClienteActionPerformed

    private void JMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenu2ActionPerformed
 
        
    }//GEN-LAST:event_JMenu2ActionPerformed

    private void GDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GDActionPerformed
        // TODO add your handling code here:
        Gananciasdia a=new Gananciasdia();
        this.Centro.add(a);
        a.show();
    }//GEN-LAST:event_GDActionPerformed

    private void RealizarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RealizarCompraActionPerformed
        // TODO add your handling code here:
        ComprasHechas a=new ComprasHechas();
        this.Centro.add(a);
        a.show();
    }//GEN-LAST:event_RealizarCompraActionPerformed

    private void PrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioActionPerformed
        ProductosenVenta a=new ProductosenVenta();
        this.Centro.add(a);
        a.show();
    }//GEN-LAST:event_PrecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administracion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Centro;
    private javax.swing.JMenuItem DatosCliente;
    private javax.swing.JMenuItem GD;
    private javax.swing.JMenu JMenu;
    private javax.swing.JMenu JMenu2;
    private javax.swing.JMenuItem Precio;
    private javax.swing.JMenuItem RealizarCompra;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
