/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package aplicativo;

import java.awt.BorderLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JLayeredPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kevin1
 */
public class ComprasHechas extends javax.swing.JInternalFrame {

   DefaultTableModel model;
    public ComprasHechas() {
        initComponents(); 
        
        setResizable(false);
        setTitle("Acceso");
        ((JPanel)getContentPane()).setOpaque(false);
        ImageIcon uno=new  ImageIcon(this.getClass().getResource("/Imagenes/Fondo4.jpg"));
        JLabel fondo=new JLabel();
        fondo.setIcon(uno);
        getLayeredPane().add(fondo,JLayeredPane.FRAME_CONTENT_LAYER);
        fondo.setBounds(0,0,uno.getIconWidth(),uno.getIconHeight());
        this.add(fondo, BorderLayout.CENTER);
        
     
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProductos = new javax.swing.JLabel();
        chkScArroz = new javax.swing.JCheckBox();
        chkScAzucar = new javax.swing.JCheckBox();
        chkPPH = new javax.swing.JCheckBox();
        chkBGalletas = new javax.swing.JCheckBox();
        chkBCaramelos = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboScArroz = new javax.swing.JComboBox();
        cboScAzucar = new javax.swing.JComboBox();
        cboPPH = new javax.swing.JComboBox();
        cboBGalletas = new javax.swing.JComboBox();
        cboBCaramelos = new javax.swing.JComboBox();
        btnTotal = new javax.swing.JButton();
        lblCos = new javax.swing.JLabel();
        txtAreaPagoTotal = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        txtLimpiar = new javax.swing.JButton();
        btnAtras = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblProductos.setText("Productos :");

        chkScArroz.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkScArroz.setForeground(new java.awt.Color(255, 255, 255));
        chkScArroz.setText("Arroz");
        chkScArroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkScArrozActionPerformed(evt);
            }
        });

        chkScAzucar.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkScAzucar.setForeground(new java.awt.Color(255, 255, 255));
        chkScAzucar.setText("Azucar");

        chkPPH.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkPPH.setForeground(new java.awt.Color(255, 255, 255));
        chkPPH.setText(" Papel Higienico");

        chkBGalletas.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkBGalletas.setForeground(new java.awt.Color(255, 255, 255));
        chkBGalletas.setText("Bolsa de Galletas");

        chkBCaramelos.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        chkBCaramelos.setForeground(new java.awt.Color(255, 255, 255));
        chkBCaramelos.setText("Bolsa de Caramelos");
        chkBCaramelos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkBCaramelosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cantidad :");

        jLabel2.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad :");

        jLabel3.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cantidad :");

        jLabel6.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Cantidad :");

        jLabel9.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Cantidad :");

        cboScArroz.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        cboScArroz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboScArrozActionPerformed(evt);
            }
        });

        cboScAzucar.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cboPPH.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cboBGalletas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        cboBCaramelos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        btnTotal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTotal.setText("Total de la Compra");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        lblCos.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        lblCos.setForeground(new java.awt.Color(255, 255, 255));
        lblCos.setText(" S/.");

        txtAreaPagoTotal.setEditable(false);

        btnEnviar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEnviar.setText("Eviar datos de ventas al cliente");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        txtLimpiar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtLimpiar.setText("Limpiar");
        txtLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLimpiarActionPerformed(evt);
            }
        });

        btnAtras.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        btnAtras.setText("Salir");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblCos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAreaPagoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42)
                                .addComponent(txtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chkBGalletas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkPPH, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblProductos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkScArroz, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkScAzucar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(chkBCaramelos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cboScArroz, 0, 50, Short.MAX_VALUE)
                            .addComponent(cboScAzucar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboPPH, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboBGalletas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboBCaramelos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(lblProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkScArroz)
                    .addComponent(jLabel1)
                    .addComponent(cboScArroz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkScAzucar)
                    .addComponent(jLabel2)
                    .addComponent(cboScAzucar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkPPH)
                    .addComponent(jLabel3)
                    .addComponent(cboPPH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBGalletas)
                    .addComponent(jLabel6)
                    .addComponent(cboBGalletas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkBCaramelos)
                    .addComponent(jLabel9)
                    .addComponent(cboBCaramelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAreaPagoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCos))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        double vnt1=0,vnt2=0,vnt3=0,vnt4=0,vnt5=0,vntT;
        double ScArroz, ScAzucar, PPH, BGalletas, BCaramelos;
        ScArroz = Double.parseDouble(cboScArroz.getSelectedItem().toString());
        ScAzucar = Double.parseDouble(cboScAzucar.getSelectedItem().toString());
        PPH = Double.parseDouble(cboPPH.getSelectedItem().toString());
        BGalletas = Double.parseDouble(cboBGalletas.getSelectedItem().toString());
        BCaramelos = Double.parseDouble(cboBCaramelos.getSelectedItem().toString());
        if(chkScArroz.isSelected())
        vnt1 = (vnt1 + 50.0) * ScArroz;
        if(chkScAzucar.isSelected())
        vnt2 = (vnt2 + 54.0) * ScAzucar;
        if(chkPPH.isSelected())
        vnt3 = (vnt3+ 35.0) * PPH;
        if(chkBGalletas.isSelected())
        vnt4 = (vnt4 + 21.0) * BGalletas;
        if(chkBCaramelos.isSelected())
        vnt5 = (vnt5 + 15.0) * BCaramelos;
        vntT = vnt1 + vnt2 + vnt3 + vnt4 + vnt5;
        txtAreaPagoTotal.setText("" + vntT);
    }//GEN-LAST:event_btnTotalActionPerformed

    private void txtLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLimpiarActionPerformed
        
        cboScArroz.setToolTipText("");
        cboScAzucar.setToolTipText("");
        cboPPH.setToolTipText("");
        cboBGalletas.setToolTipText("");
        cboBCaramelos.setToolTipText("");
        txtAreaPagoTotal.setText("");

    }//GEN-LAST:event_txtLimpiarActionPerformed

    private void cboScArrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboScArrozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboScArrozActionPerformed

    private void chkBCaramelosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkBCaramelosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkBCaramelosActionPerformed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
        Datos.txtCompra.setText(txtAreaPagoTotal.getText());
        
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void chkScArrozActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkScArrozActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkScArrozActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnTotal;
    private javax.swing.JComboBox cboBCaramelos;
    private javax.swing.JComboBox cboBGalletas;
    private javax.swing.JComboBox cboPPH;
    private javax.swing.JComboBox cboScArroz;
    private javax.swing.JComboBox cboScAzucar;
    private javax.swing.JCheckBox chkBCaramelos;
    private javax.swing.JCheckBox chkBGalletas;
    private javax.swing.JCheckBox chkPPH;
    private javax.swing.JCheckBox chkScArroz;
    private javax.swing.JCheckBox chkScAzucar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCos;
    private javax.swing.JLabel lblProductos;
    public static javax.swing.JTextField txtAreaPagoTotal;
    private javax.swing.JButton txtLimpiar;
    // End of variables declaration//GEN-END:variables
}
